# Calcular los principales indicadores de la estadística descriptiva

In [1]:
import numpy as np # importando numpy
from scipy import stats # importando scipy.stats
import pandas as pd # importando pandas

np.random.seed(2131982) # para poder replicar el random

In [2]:

datos = np.random.randn(5, 4) # datos normalmente distribuidos
datos

array([[ 0.46038022, -1.08942528, -0.62681496, -0.63329028],
       [-0.1074033 , -0.88138082, -0.34466623, -0.28320214],
       [ 0.94051171,  0.86693793,  1.20947882, -0.16894118],
       [-0.12790177, -0.58099931, -0.46188426, -0.18148302],
       [-0.76959435, -1.37414587,  1.37696874, -0.18040537]])

In [5]:
# Calcula la media aritmetica
datos.mean()

-0.14786303590303568

In [6]:
# Mismo resultado desde la funcion de numpy
np.mean(datos) 

-0.14786303590303568

In [7]:

# media aritmetica de cada fila
datos.mean(axis=1) 

array([-0.47228757, -0.40416312,  0.71199682, -0.33806709, -0.23679421])

In [8]:
# media aritmetica de cada columna
datos.mean(axis=0) 

array([ 0.0791985 , -0.61180267,  0.23061642, -0.2894644 ])

In [9]:
# mediana
np.median(datos)

-0.23234258265023794

In [10]:
# media aritmetica de cada columna
np.median(datos, 0) 

array([-0.1074033 , -0.88138082, -0.34466623, -0.18148302])

In [11]:
# Desviación típica
np.std(datos)

0.7375535458407161

In [12]:
# Desviación típica de cada columna
np.std(datos, 0) 

array([0.58057213, 0.78352862, 0.87384108, 0.17682485])

In [13]:
# varianza
np.var(datos) 

0.5439852329822132

In [14]:

# varianza de cada columna
np.var(datos, 0) 

array([0.337064  , 0.6139171 , 0.76359823, 0.03126703])

## utilizando pandas

In [18]:

df = pd.DataFrame(datos, index=['a', 'b', 'c', 'd', 'e'], 
                        columns=['Notas_2018', 'Notas_2019', 'Notas_2020', 'Notas_2021'])
df

Notas_2018  Notas_2019  Notas_2020  Notas_2021
a    0.460380   -1.089425   -0.626815   -0.633290
b   -0.107403   -0.881381   -0.344666   -0.283202
c    0.940512    0.866938    1.209479   -0.168941
d   -0.127902   -0.580999   -0.461884   -0.181483
e   -0.769594   -1.374146    1.376969   -0.180405

In [19]:
# resumen estadistadistico
df.describe()

Notas_2018  Notas_2019  Notas_2020  Notas_2021
count    5.000000    5.000000    5.000000    5.000000
mean     0.079199   -0.611803    0.230616   -0.289464
std      0.649099    0.876012    0.976984    0.197696
min     -0.769594   -1.374146   -0.626815   -0.633290
25%     -0.127902   -1.089425   -0.461884   -0.283202
50%     -0.107403   -0.881381   -0.344666   -0.181483
75%      0.460380   -0.580999    1.209479   -0.180405
max      0.940512    0.866938    1.376969   -0.168941

In [20]:
# sumando las columnas
df.sum()

Notas_2018    0.395993
Notas_2019   -3.059013
Notas_2020    1.153082
Notas_2021   -1.447322
dtype: float64

In [21]:
# sumando filas
df.sum(axis=1)

a   -1.889150
b   -1.616652
c    2.847987
d   -1.352268
e   -0.947177
dtype: float64

In [22]:
# media aritmetica de cada columna
df.mean()

Notas_2018    0.079199
Notas_2019   -0.611803
Notas_2020    0.230616
Notas_2021   -0.289464
dtype: float64

In [23]:
# media aritmetica de cada fila
df.mean(axis=1)

a   -0.472288
b   -0.404163
c    0.711997
d   -0.338067
e   -0.236794
dtype: float64